mode: daemonset
config:
  exporters:
    otlp:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "$HONEYCOMB_APIKEY"
        "X-Honeycomb-Dataset": "MYDATASET"
  service:
    pipelines:
      traces:
        exporters: [ otlp ]
      metrics:
        exporters: [ otlp ]
      logs:
        exporters: [ otlp ]

extraEnvs:
  - name: HONEYCOMB_APIKEY
    valueFrom:
      secretKeyRef:
        name: honeycomb-apikey 
        key: HONEYCOMB_APIKEY

presets:
  logsCollection:
    enabled: true
  hostMetrics:
    enabled: true
  kubeletMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
