mode: deployment
config:
  exporters:
    otlp:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "$HONEYCOMB_APIKEY"
        "X-Honeycomb-Dataset": "METRIC_DATASET_NAME"
  service:
    pipelines:
      traces:
        exporters: [ otlp ]
      metrics:
        exporters: [ otlp ]
      logs:
        exporters: [ otlp ]

extraEnvs:
  - name: HONEYCOMB_APIKEY
    valueFrom:
      secretKeyRef:
        name: honeycomb-apikey 
        key: HONEYCOMB_APIKEY

presets:
  kubernetesAttributes:
    enabled: true
  kubernetesEvents:
    enabled: true
  clusterMetrics:
    enabled: true