mode: daemonset
config:
  exporters:
    otlp:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "MYAPIKEY"
        "X-Honeycomb-Dataset": "MYDATASET"
  service:
    pipelines:
      traces:
        exporters: [ otlp ]
      metrics:
        exporters: [ otlp ]
      logs:
        exporters: [ otlp ]
presets:
  logsCollection:
    enabled: true
  hostMetrics:
    enabled: true
  kubeletMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
