kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: versions-test
  name: developer-rolebinding
subjects:
- kind: Group
  name: development-team
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: versions-test
  name: operator-rolebinding
subjects:
- kind: User
  name: operator-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: operator-role
  apiGroup: rbac.authorization.k8s.io
