apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: -skaffold
build:
  artifacts:
  - image: skaffoldtest
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
