---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /test_volume/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-volume
spec:
  volumeName: pv-test-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      