name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.7.0
        with:
          name: kind
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
              - role: control-plane
                extraPortMappings:
                  - containerPort: 30080
                    hostPort: 80
                    protocol: TCP
                  - containerPort: 30443
                    hostPort: 443
                    protocol: TCP
              - role: worker
      - name: Install Helm
        run: |
          kubectl version
          

